### PR TITLE
Fix/air: Deprecated GOPATH reliability

### LINKED ISSUE #74: Current `make watch` target fails to find `air` even after successful installation
## Description
When running `make watch` after successfully installing `air`, the Makefile still prompts "air is not installed. Do you want to install it now? (y/n)". This happens even though `air` has been installed and is available in the PATH. 

It seems like the GOPATH has been deprecated in Go 1.16 and should not be relied on.

## Environment
- Go version: 1.21.0
- OS: Ubuntu 22.04

## Additional Information
Here is the `watch` target in the Makefile:

```makefile
watch:
	@if [ -x "$(GOPATH)/bin/air" ]; then \
	    "$(GOPATH)/bin/air"; \
		@echo "Watching...";\
	else \
	    read -p "air is not installed. Do you want to install it now? (y/n) " choice; \
	    if [ "$$choice" = "y" ]; then \
			go install github.com/cosmtrek/air@latest; \
	        "$(GOPATH)/bin/air"; \
				@echo "Watching...";\
	    else \
	        echo "You chose not to install air. Exiting..."; \
	        exit 1; \
	    fi; \
	fi

### PR DESCRIPTION
**Pull request by andrerocco**
Closes #74

### CODE REVIEW

**Review by 20pa5a1210 — APPROVED** [review]
Tested it locally working perfectly fine good to go

**Comment by andrerocco** [comment]
Heyy @Melkeydev, what Go version are you using? Curious how people didn't get this error before. Maybe most people have GOPATH in their enviroment.

**Comment by Melkeydev** [comment]
@andrerocco Can you rebase to resolve the linting check and the conflicts? I would like to merge this PR. It looks good

**Comment by andrerocco** [comment]
@Melkeydev Sorry for the late response but sure, doing that now!

**Comment by andrerocco** [comment]
Fixed at #109; @Melkeydev

**Comment by andrerocco** [comment]
Fixed at #109; @Melkeydev

**Pull request closed without merging**
