### PR TITLE
feat ✨: added repo templates to go-blueprint repo

### PR DESCRIPTION
**Pull request by muandane**
@Melkeydev can you add this it's template for Feature requests and issues and PRs

### CODE REVIEW

**Comment by Melkeydev** [comment]
@muandane We seem to have added other workflow files to have issues and features.
Are you proposing to replace the current ones with this PR?

**Comment by muandane** [comment]
@Melkeydev i added this PR before spiro but since spiro's pr got merged I closed this since there's no use to it

**Comment by SputNikPlop** [comment]
I like the new addition to the project perhaps we could keep that one

**Comment by Melkeydev** [comment]
@muandane I am going to close this one - however if you want to add a further PR that adds some improvements that would be great.
Sorry about this

**Pull request closed without merging**
