### PR TITLE
Gives an error if a directory already exists. Colorized the errors when doing `create` if occurred

### PR DESCRIPTION
**Pull request by Jamlie**
I made the project check the availability the given directory, if it does exist and it's not empty, it gives an error and exits.

The error messages when creating a project - if occurred - are now colored with #FF8700

### CODE REVIEW

**Review by Melkeydev — APPROVED** [review]
LGTM

**Comment by Melkeydev** [comment]
@Jamlie Please rebase - as the current PR is failing on linting checks that were fixed in a previous PR!

**Comment by Jamlie** [comment]
@Melkeydev it's done, it's ready to be merged!

**Review by Melkeydev — APPROVED** [review]
LGTM BOIIIII

**Pull request merged**
