### PR TITLE
ci: linting on generated code

### LINKED ISSUE #39: Linting on generated code
PR #28 adds a workflow for linting the cli code but this does not lint the template code since that is just a string in the go code. Maybe it would be nice to have CI generate all templates to run the linter on those as well. That users don't have to manually check the generated code with the linter.

### PR DESCRIPTION
**Pull request by mimatache**
This PR will run `golangci-lint` against all the generated repositories.

Things to improve:
- ~~Don't install `golangci-lint` for each item in the matrix~~ 
- Uses `golangci-lint` predefined action
- Add a `.golangci.yaml` file with desired linter configuration

resolve #39

### CODE REVIEW

**Comment by Melkeydev** [comment]
Checking out this PR and on your local branch I see that all the builds are failing :thinking: 
https://github.com/mimatache/go-blueprint/actions

Is there working pipelines that I can see :sweat:

**Comment by mimatache** [comment]
> Checking out this PR and on your local branch I see that all the builds are failing 🤔 https://github.com/mimatache/go-blueprint/actions
> 
> Is there working pipelines that I can see 😓

What is failing is not the new workflow, but the one was already failing the main repository earlier that is breaking my actions as well:
image

I can't seem to get the actions to trigger right now (didn't even see them running on mine before). Do you have any advice on how to get them to run (note, my workflow might not event start until it was merged into main).

**Comment by mimatache** [comment]
@Melkeydev can you try approving the workflows so we can see if they run/pass here? I don't have the option from my branch to run it.

**Review by Melkeydev — APPROVED** [review]
LGTM

**Pull request merged**
