### PR TITLE
add check for git config

### PR DESCRIPTION
**Pull request by briancbarrow**
By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## Problem/Feature

Address #159 

## Description of Changes: 

- adds check for git config name and email

## Checklist

- [x] I have self-reviewed the changes being requested
- [x] I have updated the documentation (if applicable)

### CODE REVIEW

**Comment by Ujstor** [comment]
Works as expected proper log if user and pass in git are not set. Terminal issue caused by the spinner will be resolved in a separate PR.

WindowsTerminal_t43i2llIV8

**Review by Ujstor — APPROVED** [review]
LGTM

**Comment by Melkeydev** [comment]
> Works as expected proper log if user and pass in git are not set. Terminal issue caused by the spinner will be resolved in a separate PR.
> 
> WindowsTerminal_t43i2llIV8

Is there a ticket/current work being done for the terminal spinner issue?

**Comment by Ujstor** [comment]
briancbarrow is working on this issue.

**Pull request merged**
