### PR TITLE
Removing brew packages in go-releaser

### PR DESCRIPTION
**Pull request by Melkeydev**
By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## Problem/Feature

Please include a description of the problem or feature this PR is addressing.

## Description of Changes: 

- Item 1
- Item 2

## Checklist

- [ ] I have self-reviewed the changes being requested
- [ ] I have updated the documentation (if applicable)

### CODE REVIEW

**Review by mikelerch — APPROVED** [review]
LGTM, but please make sure unrelated whitespace changes are addressed in a separate PR from now on. Preferably a linter for YAML files is introduced as well, or at the least, an `.editorconfig`.

**Comment by Ujstor** [comment]
This is ok

**Comment by muandane** [comment]
Yes that should be it for brew removal

**Comment by muandane** [comment]
although can you check what's the scope on the github token ? for example this is the token i use for my goreleaser pipeline (i just want to know why it's broken not force adding brew installation to this repo)
image

**Comment by muandane** [comment]
btw need to remove brew install method in README.md

**Comment by Ujstor** [comment]
@muandane  There is my PR with changes in readme, I have removed 'brew install' from it

**Comment by Melkeydev** [comment]
> although can you check what's the scope on the github token ? for example this is the token i use for my goreleaser pipeline (i just want to know why it's broken not force adding brew installation to this repo) image

I am not sure how to find this token - can you DM on discord to instruct me where to find the scopes?

**Pull request merged**
