### PR TITLE
added a spinner

### PR DESCRIPTION
**Pull request by MohammadAlhallaq**
https://github.com/Melkeydev/go-blueprint/assets/19909432/443ad687-6d38-4797-a739-0bc1c76763d8

### CODE REVIEW

**Comment by Melkeydev** [comment]
> Screen.Recording.2023-11-05.at.11.54.36.PM.mov

This looks beautiful

**Comment by Melkeydev** [comment]
Any updates on this? anything I can help out on?

**Comment by MohammadAlhallaq** [comment]
> Any updates on this? anything I can help out on?

Actually, there are two things to address:

1- I encountered a minor bug while working on it, so I'm currently waiting until I finish implementing the database functionality before attempting to reproduce the bug and resolve it.

2- I'm not entirely convinced by the way I implemented this, and I want to ensure that there is no way to make the spinner model run asynchronously without blocking the main routine without the need to run it on a separate goroutine.

So, I'm just waiting to finish working on my first PR.

**Review by Melkeydev — APPROVED** [review]
LGTM

**Comment by Melkeydev** [comment]
Closing this one due to #96

**Pull request closed without merging**
